# Generated by Django 4.2.6 on 2023-10-22 06:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('last_visit_date', models.DateTimeField(auto_now_add=True)),
                ('next_visit_date', models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 40, 48, 37584))),
            ],
        ),
    ]
